# [WineGUI](https://gitlab.melroy.org/melroy/winegui) is a user-interface
# friendly Wine manager that provides a graphical frontend for creating and
# managing Wine bottles.

---
services:
  winegui:
    image: lscr.io/linuxserver/winegui:latest
    container_name: winegui
    environment:
      # Run 'id [USER]' for the owner of the host volume directories to get the UID to use here.
      - PUID=${PUID:-1000}
      # Run 'id [USER]' for the owner of the host volume directories to get the GID to use here.
      - PGID=${PGID:-1000}
      # specify a timezone to use, see this [list](https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List).
      - TZ=${TZ:-Etc/UTC}
    volumes:
      # Users home directory in the container, stores local files and settings
      - ${BASEDIR:-/srv/lsio}/winegui/config:/config
    ports:
      # HTTP WineGUI, must be proxied.
      - 3000:3000
      # HTTPS WineGUI.
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped